---
title: "Schedule"
format: 
  html:
    link-external-newwindow: true
    page-layout: full
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
library(here)
source(here("class_dates.R"))
```

| Week | Date | Chapter | Topic | Key Info | Slides QMD | Slides PDF | Slides Notes | Exit tix | Record-ing | Muddy Points |
|-------|-------|-------|-------|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|:-----:|
| 1 | `{r} w1d1` |  | Welcome | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/00_Intro/00_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/00_Intro/00_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/00_Intro/00_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 1 | Outcomes, Events, and Sample Space | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/01_Outcomes_Events_Sample/01_Outcomes_Events_Sample.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/01_Outcomes_Events_Sample/01_Outcomes_Events_Sample.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w1d2` | 2 | Probability | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/02_Probability/02_Probability_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/02_Probability/02_Probability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/02_Probability/02_Probability.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw0`**]{style="color:#006a4e;"} |  | [**HW 0 due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 2 | `{r} w2d1` | 22 | Introduction to Counting | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/22_Counting_Intro/22_Counting_Intro_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/22_Counting_Intro/22_Counting_Intro.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/22_Counting_Intro/22_Counting_Intro.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 3 | Independent Events |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/03_Independent_Events/03_Independent_Events.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/03_Independent_Events/03_Independent_Events.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `{r} w2d2` | 4 | Conditional Probability | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/04_Conditional_Probability/04_Conditional_Probability_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/04_Conditional_Probability/04_Conditional_Probability.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/04_Conditional_Probability/04_Conditional_Probability.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 5 | Bayes Theorem |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/05_Bayes_Theorem/05_Bayes_Theorem.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/05_Bayes_Theorem/05_Bayes_Theorem.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw1`**]{style="color:#006a4e;"} |  | [**HW 1 due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 3 | `r w3d1` | 7 | Random Variables | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/07_Random_Variables/07_Random_Variables_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/07_Random_Variables/07_Random_Variables.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/07_Random_Variables/07_Random_Variables.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 8 | pmfs and CDFs | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/08_pmfs_and_cdfs/08_pmfs_and_cdfs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/08_pmfs_and_cdfs/08_pmfs_and_cdfs.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w3d2` | 14-20 | Some Important Discrete RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/14_20_Discrete_RVs/14_20_Discrete_RVs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/14_20_Discrete_RVs/14_20_Discrete_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/14_20_Discrete_RVs/14_20_Discrete_RVs.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw2`**]{style="color:#006a4e;"} |  | [**HW 2 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 4 | `r w4d1` | 9 | Independence and Conditioning (Joint Distributions) | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/09_Joint_distributions/09_Joint_distributions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/09_Joint_distributions/09_Joint_distributions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/09_Joint_distributions/09_Joint_distributions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w4d2` |  | Class canceled |  |  |  |  |  |  |  |
|  | [**`r hw3`**]{style="color:#006a4e;"} |  | [**HW 3 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw2sol`**]{style="color:#006a4e;"} |  | [**HW 2 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 5 | `r w5d1` | 10 | Expected Values of discrete RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/10_Expected_Values/10_Expected_Values_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/10_Expected_Values/10_Expected_Values.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/10_Expected_Values/10_Expected_Values.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 11 | Expected Values of *sums of* discrete RVs |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/11_Expected_Values_of_Sums_of_rvs/11_Expected_Values_of_Sums_of_rvs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/11_Expected_Values_of_Sums_of_rvs/11_Expected_Values_of_Sums_of_rvs.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w5d2` | 12 | Variance of discrete RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/12_Variance/12_Variance_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/12_Variance/12_Variance.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/12_Variance/12_Variance.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw4`**]{style="color:#006a4e;"} |  | [**HW 4 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw3sol`**]{style="color:#006a4e;"} |  | [**HW 3 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 6 | `r w6d1` | pre-24 | Calculus Review | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/24_00_Calculus_review/24_00_Calculus_review_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/24_00_Calculus_review/24_00_Calculus_review.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/24_00_Calculus_review/24_00_Calculus_review.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w6d2` | 24 | Continuous RVs and PDFs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/24_01_Continuous_rv/24_01_Continuous_rv_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/24_01_Continuous_rv/24_01_Continuous_rv.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/24_01_Continuous_rv/24_01_Continuous_rv.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw5`**]{style="color:#006a4e;"} |  | [**HW 5 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw4sol`**]{style="color:#006a4e;"} |  | [**HW 4 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 7 | `r w7d1` | 28 | Expected value of continuous RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/28_Expected_Values/28_Expected_Values_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/28_Expected_Values/28_Expected_Values.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/28_Expected_Values/28_Expected_Values.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 29 | Variance of continuous RVs | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/29_Variance_and_Sums_of_rv/29_Variance_and_Sums_of_rv.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/29_Variance_and_Sums_of_rv/29_Variance_and_Sums_of_rv.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw3prez`**]{style="color:#006a4e;"} |  | [**HW 3 videos due 11pm, if meeting with Nicky, schedule for some time this week**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | `r w7d2` | 31-35 | Some Important Continuous RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/31_35_Cont_RVs/31_35_Cont_RVs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/31_35_Cont_RVs/31_35_Cont_RVs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/31_35_Cont_RVs/31_35_Cont_RVs.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw6`**]{style="color:#006a4e;"} |  | [**HW 6 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw5sol`**]{style="color:#006a4e;"} |  | [**HW 5 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 8 | `r w8d1` |  | Class canceled, Nicky sick |  |  |  |  |  |  |  |
|  | `r w8d2` | 25 | Joint Densities[^1] | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/25_Joint_densities/25_Joint_densities_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/25_Joint_densities/25_Joint_densities.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/25_Joint_densities/25_Joint_densities.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw7`**]{style="color:#006a4e;"} |  | [**HW 7 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw6sol`**]{style="color:#006a4e;"} |  | [**HW 6 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 9 | `r w9d1` | 26 | Independent continuous RVs[^2] | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/26_Independent_rvs/26_Independent_rvs_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/26_Independent_rvs/26_Independent_rvs.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/26_Independent_rvs/26_Independent_rvs.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 27 | Conditional distributions[^3] | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/27_Conditional_distributions/27_Conditional_distributions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/27_Conditional_distributions/27_Conditional_distributions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 28-29 | Expected values and variance revisited[^4] |  | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/28_29_Joint_expected_value_Variance/28_29_Joint_expected_value_Variance.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/28_29_Joint_expected_value_Variance/28_29_Joint_expected_value_Variance.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w9d2` |  | No class |  |  |  |  |  |  |  |
|  | [**`r hw7sol`**]{style="color:#006a4e;"} |  | [**HW 7 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 10 | `r w10d1` | 36 | Sums of independent normal RVs | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/36_Sums_of_Independent_Normal_rv/36_Sums_of_Independent_Normal_rv_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/36_Sums_of_Independent_Normal_rv/36_Sums_of_Independent_Normal_rv.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/36_Sums_of_Independent_Normal_rv/36_Sums_of_Independent_Normal_rv.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  |  | 37 | Central limit theorem | [{{< iconify akar-icons info-fill size=30px >}}]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/37_Central_Limit_Theorem/37_Central_Limit_Theorem.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/37_Central_Limit_Theorem/37_Central_Limit_Theorem.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | `r w10d2` | 43 | Moment generating functions | [[{{< iconify akar-icons info-fill size=30px >}}](lessons/43_01_Moment_Generating_Functions/43_01_Moment_Generating_Functions_key_info.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify ri slideshow-fill size=30px >}}](lessons/43_01_Moment_Generating_Functions/43_01_Moment_Generating_Functions.qmd)]{style="color:#f8f5f0;"} | [[{{< iconify bi file-earmark-pdf-fill size=28px >}}](lessons/43_01_Moment_Generating_Functions/43_01_Moment_Generating_Functions.pdf)]{style="color:#f8f5f0;"} | [{{< iconify pepicons-pop pen-circle-filled size=29px >}}]{style="color:#f8f5f0;"} | [{{< iconify healthicons health-worker-form size=32px >}}]{style="color:#f8f5f0;"} | [{{< iconify mdi video size=34px >}}]{style="color:#f8f5f0;"} | [{{< iconify pajamas question size=30px >}}]{style="color:#f8f5f0;"} |
|  | [**`r hw8`**]{style="color:#006a4e;"} |  | [**HW 8 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw7prez`**]{style="color:#006a4e;"} |  | [HW 7 presentations due 11pm (with meetings 12/9-12/11)]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  |  |  |  |  |  |  |  |  |  |  |
| 11 | `r w11d1` |  | No class!! |  |  |  |  |  |  |  |
|  | [**`r hw9`**]{style="color:#006a4e;"} |  | [**Optional HW 9 due 11 pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |
|  | [**`r hw8sol`**]{style="color:#006a4e;"} |  | [**HW 8 solutions due 11pm**]{style="color:#006a4e;"} |  |  |  |  |  |  |  |

: {.striped .hover tbl-colwidths="\[6, 6, 6, 46,6, 6, 6, 6, 6, 6, 6\]"}

[^1]: [Here's a link to Meike's recordings for certain problems that I said to do at home.](https://ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_BSTA_550/Student_files_BSTA_550/Meike_recording?csf=1&web=1&e=9HkR4d)

[^2]: [Here's a link to Meike's recordings for certain problems that I said to do at home.](https://ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_BSTA_550/Student_files_BSTA_550/Meike_recording?csf=1&web=1&e=9HkR4d)

[^3]: [Here's a link to Meike's recordings for certain problems that I said to do at home.](https://ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_BSTA_550/Student_files_BSTA_550/Meike_recording?csf=1&web=1&e=9HkR4d)

[^4]: [Here's a link to Meike's recordings for certain problems that I said to do at home.](https://ohsuitg-my.sharepoint.com/:f:/r/personal/wakim_ohsu_edu/Documents/Teaching/Classes/F24_BSTA_550/Student_files_BSTA_550/Meike_recording?csf=1&web=1&e=9HkR4d)
