---
title: "Key Info"
date-modified: "today"
format: 
  html:
    link-external-newwindow: true
editor_options: 
  chunk_output_type: console
---

## Announcements

- Q: Can we still turn in exit tickets even if its not the same day? For example I was here the first day but forgot to do the exit ticket, if I did it today would it still count towards my grade?
  - Yes! I check them for "attendance" after 7 (sometimes more) days after the class

- For muddy points, it really helps if you can asked a specific question about what you found confusing
  - I can then address it in a more targeted way

- For office hours, we decided to do appointments!
  - Here's my Calendly: <https://calendly.com/nickywakim/15min>
  - I teach on Mondays and Wednesdays so I am keeping most of my meetings to Tuesdays and Thursdays
  - For my EPI class, I have scheduled office hours on Mondays 4-5pm in VPT 627
    - I will give priority to EPI students, but you can drop by for those as well
    
- I think all the dates in the schedule were correct except for next week

## Key Dates

- HW 1 Assignment due this Thursday at 11pm
